version: '3.1'

services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - devdojo-db:/var/lib/mysql
volumes:
  devdojo-db:
