server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/address_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ROOT_USERNAME:root}
    password: ${ROOT_PASSWORD:example}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update